### ISSUE TITLE
Необоснованное переопределение дефолтного ЖЦ

### ISSUE THREAD

**Issue by coursar** [Melnioks/netology_test#2]
https://github.com/Melnioks/netology_test/blob/26331d6b519e2de5dc4453029cc89c7c2686d7da/src/test/java/netology/CashbackHackServiceTest.java#L11-L14

Не стоит переопределять дефолтный ЖЦ ради инстанцирования одного лёгкого сервиса

**Comment by Melnioks** [comment]
fixed
