### ISSUE TITLE
Неплохо бы в тестовые данные включить message, который затем прокидывать в assetEquals

### ISSUE THREAD

**Issue by coursar** [Melnioks/netology_test#3]
https://github.com/Melnioks/netology_test/blob/26331d6b519e2de5dc4453029cc89c7c2686d7da/src/test/java/netology/CashbackHackServiceTest.java#L19

**Comment by Melnioks** [comment]
fixed

**Comment by Melnioks** [comment]
fixed by commit 9b108d10bd348056da6a3c832099372cd89af8cc
